# CodeToGraph Configuration Example
# Copy this file to settings.yaml and customize as needed

# Application settings
app:
  name: "CodeToGraph"
  version: "0.1.0"
  debug: false

# Neo4j database configuration
neo4j:
  uri: "bolt://localhost:7687"
  username: "neo4j"
  password: "password123"
  database: "neo4j"
  max_connection_lifetime: 3600
  max_connection_pool_size: 50

# LLM configuration
llm:
  # Primary provider: openai, ollama, local
  provider: "ollama"
  
  # OLLAMA settings (recommended)
  ollama_base_url: "http://localhost:11434"
  ollama_model: "qwen3:1.7b"
  
  # General settings
  max_tokens: 2048
  temperature: 0.1
  timeout: 120
  
  # Query optimization
  enable_caching: true
  cache_ttl: 3600

# Repository processing settings
processing:
  # Chunking configuration
  chunk_strategy: "hybrid"  # package, size, hybrid
  max_chunk_size: 100
  max_memory_gb: 16
  
  # Parser settings
  enable_tree_sitter: true
  enable_joern: true
  joern_heap_size: "8G"
  
  # Supported languages
  supported_languages:
    - "go"
    - "java"
    - "python"
    - "javascript"
    - "typescript"
  
  # File filtering
  exclude_patterns:
    - "**/test/**"
    - "**/tests/**" 
    - "**/*_test.go"
    - "**/*Test.java"
    - "**/node_modules/**"
    - "**/vendor/**"
    - "**/.git/**"
    - "**/build/**"
    - "**/dist/**"
    - "**/*.min.js"
  
  # Incremental processing
  enable_incremental: true
  track_file_hashes: true

# Visualization settings
visualization:
  # Server settings
  host: "localhost"
  port: 8080
  debug: false
  
  # Graph rendering
  max_nodes_per_view: 1000
  default_layout: "force"
  enable_physics: true
  
  # Hierarchical navigation
  enable_drill_down: true
  hierarchy_levels:
    - "repository"
    - "package"
    - "class"
    - "function"

# Directory paths
paths:
  data_dir: "./data"
  cache_dir: "./cache"
  logs_dir: "./logs"
  temp_dir: "./tmp"

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name}:{function}:{line} - {message}"

# Performance tuning
performance:
  # Neo4j import settings
  csv_batch_size: 10000
  transaction_size: 1000
  
  # Memory limits
  parser_memory_limit: "8G"
  import_memory_limit: "16G"
  
  # Parallel processing
  max_worker_threads: 4
  
  # Caching
  enable_file_cache: true
  cache_compression: true